PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
DELETE {?glossary dcterms:title ?title}
INSERT {?glossary skos:prefLabel ?title}
WHERE {?glossary dcterms:title ?title ; a skos:ConceptScheme}