#!/bin/bash
FILES=$(git diff --name-only master..${CIRCLE_BRANCH} -- '*.ttl')
for f in $FILES
do
  echo "***********"
  echo "DIFF for $f"
  echo "***********"
  git difftool master..${CIRCLE_BRANCH} $f -y -x .owldiff/git-owldiff
done
